# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

references:
  docker_default: &docker_default
    environment:
      TZ: "/usr/share/zoneinfo/Asia/Taipei"
    docker:
      - image: circleci/node:8.8.1
  yarn_cache_key: &yarn_cache_key
    v2-yarn-cache-{{ checksum "yarn.lock" }}
  build_cache_key: &build_cache_key
    build-cache-{{ checksum "version.json" }}
  restore_node_modules: &restore_node_modules
    restore_cache:
      key: *yarn_cache_key
  restore_build: &restore_build
    restore_cache:
      key: *build_cache_key
  persist_to_workspace: &persist_to_workspace
    persist_to_workspace:
      root: .
      paths:
        - ./*
  attach_workspace: &attach_workspace
    attach_workspace:
      at: .

jobs:
  bootstrap:
    <<: *docker_default
    steps:
      - checkout
      - *persist_to_workspace
      - *restore_node_modules
      - run:
          name: yarn dependencies
          command: yarn install --pure-lockfile
      - save_cache:
          key: *yarn_cache_key
          paths:
            - .cache/yarn
            - node_modules
  test:
    <<: *docker_default
    steps:
      - *attach_workspace
      - *restore_node_modules
      - run:
          name: test
          command: yarn test
  build:
    <<: *docker_default
    steps:
      - *attach_workspace
      - *restore_node_modules
      - run:
          name: build
          command: yarn build
      - save_cache:
          key: *build_cache_key
          paths:
            - build
  bundlesize:
    <<: *docker_default
    steps:
      - *attach_workspace
      - *restore_node_modules
      - *restore_build
      - run:
          name: bundlesize
          command: yarn bundlesize
  danger:
    <<: *docker_default
    steps:
      - *attach_workspace
      - *restore_node_modules
      - *restore_build
      - run: yarn danger ci

workflows:
  version: 2
  all:
    jobs:
      - bootstrap
      - test:
          requires:
            - bootstrap
      - build:
          requires:
            - bootstrap
      - danger:
          requires:
            - build